version: '3.8'


services:
    mysql-auth:
      image: mysql:8
      environment:
        MYSQL_DATABASE: auth_db
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - "3316:3306"

    mysql-product:
      image: mysql:8
      environment:
        MYSQL_DATABASE: product_db
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - "3307:3306"


    mysql-order:
      image: mysql:8
      environment:
        MYSQL_DATABASE: order_db
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      ports:
        - "3308:3306"


    mongodb:
      image: mongo:7
      environment:
        MONGO_INITDB_DATABASE: notification_db
      ports:
        - "27017:27017"

    rabbitmq:
      image: rabbitmq:3-management
      ports:
        - "5672:5672"
